### ISSUE TITLE
Empty fields should not be output

### ISSUE THREAD

**Issue by vsoch** [buildsi/Smeagle#18]
E.g., this

```yaml
# ./build/standalone/Smeagle -l ./build/test/libdirectionality.so 
library: "./build/test/libdirectionality.so"
locations: 
  - function:
      name: _Z3fooi
      parameters:
        - name: x
          type: int
          location: framebase+8
          direction: import
  - function:
      name: _init
      parameters:
  - function:
      name: _fini
      parameters:
```
Should just be:

```yaml
# ./build/standalone/Smeagle -l ./build/test/libdirectionality.so 
library: "./build/test/libdirectionality.so"
locations: 
  - function:
      name: _Z3fooi
      parameters:
        - name: x
          type: int
          location: framebase+8
          direction: import
  - function:
      name: _init
  - function:
      name: _fini
```
